# Generated by Django 5.1.4 on 2025-01-26 01:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name_plural": "Users"},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name_plural": "Posts"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name_plural": "Tags"},
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="blog.author",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(
                validators=[django.core.validators.MinLengthValidator(5)]
            ),
        ),
    ]
