# Generated by Django 5.1.4 on 2025-01-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_author_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name_plural": "tag"},
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(upload_to="posts"),
        ),
    ]
