# Generated by Django 5.1.4 on 2025-01-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="date",
            field=models.DateField(auto_now=True),
        ),
    ]
